// Objective type enums
export enum ObjectiveType {
  CONQUER_CONTINENTS = 'CONQUER_CONTINENTS',
  CONQUER_TERRITORIES = 'CONQUER_TERRITORIES',
  ELIMINATE_PLAYER = 'ELIMINATE_PLAYER',
  TERRITORIES_WITH_TROOPS = 'TERRITORIES_WITH_TROOPS',
  NUMBER_OF_WORLD_COUNTRIES = 'NUMBER_OF_WORLD_COUNTRIES'
}
