// Player status enums
export enum PlayerState {
  CONNECTED = 'CONNECTED',
  DISCONNECTED = 'DISCONNECTED',
  WAITING = 'WAITING',
  PLAYING = 'PLAYING',
  ELIMINATED = 'ELIMINATED',
  WINNER = 'WINNER'
}
