// Special rule enums
export enum SpecialRule {
  EXTRA_INITIAL_TROOPS = 'EXTRA_INITIAL_TROOPS',
  UNLIMITED_FORTIFICATION = 'UNLIMITED_FORTIFICATION',
  CARDS_PER_TURN = 'CARDS_PER_TURN',
  QUICK_CONQUEST = 'QUICK_CONQUEST',
  CHAIN_ATTACK = 'CHAIN_ATTACK'
}
